name: fire_game_infra
description: "A new Flutter project."
version: 0.0.1

environment:
  sdk: ^3.4.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^5.5.0
  either_dart: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
